const data = [
  {
    id: 1,
    title: "Power Rack - Mir Fitness",
    detail: "Estación completa para ejercicios compuestos, ideal para el gimnasio en casa.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Power-rack-Mir-Fitness-1000x1000.jpg",
    price: 700,
    stock: 10,
    category: "Equipamiento",
  },
  {
    id: 2,
    title: "Rack de Sentadillas - Mir Fitness",
    detail: "Diseñado para entrenar piernas con seguridad y estabilidad.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Rack-de-sentadillas-Mir-Fitness-1-1000x1000.jpg",
    price: 500,
    stock: 15,
    category: "Equipamiento",
  },
  {
    id: 3,
    title: "Plataforma para Sentadillas Sumo",
    detail: "Accesorio esencial para optimizar la técnica en sentadillas sumo.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Plataforma-para-sentadillas-Sumo-Mir-Fitness-1000x1000.jpg",
    price: 480,
    stock: 20,
    category: "Accesorios",
  },
  {
    id: 4,
    title: "Cinta de Correr - Starke",
    detail: "Cinta profesional para entrenamientos de cardio intensos.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Cinta-Starke-1000x1000.jpg",
    price: 2700,
    stock: 5,
    category: "Equipamiento",
  },
  {
    id: 5,
    title: "Mancuernas Hexagonales 15 kg",
    detail: "Par de mancuernas de caucho ideales para entrenamientos de fuerza.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Mancuernas-Hexagonales-de-Caucho-Mir-de-15-Kg-2-2-1000x1000.jpg",
    price: 150,
    stock: 50,
    category: "Pesas",
  },
  {
    id: 6,
    title: "Set de Mancuernas Redondas 25-30 kg",
    detail: "Conjunto de 12 pares de mancuernas para sesiones de alto rendimiento.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Set-de-mancuernas-de-goma-redondas-sin-logo-de-25kg-a-30kg.-Total-390kg-12-pares-1000x1000.jpg",
    price: 3900,
    stock: 2,
    category: "Pesas",
  },
  {
    id: 7,
    title: "Mancuernas Everlast Recubiertas",
    detail: "Mancuernas recubiertas en goma para mayor durabilidad.",
    img: "https://mirfitness.com.ar/wp-content/uploads/mancuernas-rec-en-goma-everlast-2-1000x1000.jpg",
    price: 550,
    stock: 10,
    category: "Pesas",
  },
  {
    id: 8,
    title: "Tobillera de Peso 2 kg",
    detail: "Tobillera ajustable para entrenamientos de resistencia.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Tobillera-de-2kg-nuevo-disen%CC%83o-1000x1000.jpg",
    price: 47,
    stock: 100,
    category: "Accesorios",
  },
  {
    id: 9,
    title: "Tobillera de Peso 3 kg",
    detail: "Añade intensidad a tus entrenamientos con estas tobillera de peso extra.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Tobillera-de-3-Kg-MIR-Con-Ribete-2-1-1000x1000.jpg",
    price: 65,
    stock: 80,
    category: "Accesorios",
  },
  {
    id: 10,
    title: "Tobillera de Peso 1.5 kg",
    detail: "Ideal para principiantes o ejercicios de rehabilitación.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Tobillera-de-1.5-KG-MIR-1-2-1000x1000.jpg",
    price: 30,
    stock: 70,
    category: "Accesorios",
  },
  {
    id: 11,
    title: "Power Rack Premium",
    detail: "Rack con diseño robusto para entrenamientos avanzados.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Power-Rack-1000x1000.jpg",
    price: 3500,
    stock: 8,
    category: "Equipamiento",
  },
  {
    id: 12,
    title: "Maquina multiejercicios",
    detail: "Juego de pesas perfectas para ejercicios dinámicos.",
    img: "https://mirfitness.com.ar/wp-content/uploads/w4-01-2.jpeg",
    price: 520,
    stock: 30,
    category: "Pesas",
  },
];

