const data = [
  {
    id: 1,
    title: "Ángeles Ensangrentados - Remera",
    detail: "Remera de algodón suave con estampado único.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Power-rack-Mir-Fitness-1000x1000.jpg",
    price: 7,
    stock: 100,
    category: "T-shirt",
  },
  {
    id: 2,
    title: "Patrulla de Esquí - Camiseta",
    detail: "Camiseta deportiva de invierno, transpirable y cómoda.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Rack-de-sentadillas-Mir-Fitness-1-1000x1000.jpg",
    price: 5,
    stock: 73,
    category: "T-shirt",
  },
  {
    id: 3,
    title: "Ladybird Ladybird - Remera",
    detail: "Remera casual de algodón, ideal para cualquier ocasión.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Plataforma-para-sentadillas-Sumo-Mir-Fitness-1000x1000.jpg",
    price: 48,
    stock: 99,
    category: "T-shirt",
  },
  {
    id: 4,
    title: "Cannonball Run II - Jeans",
    detail: "Jeans clásicos, cómodos y perfectos para combinar.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Cinta-Starke-1000x1000.jpg",
    price: 27,
    stock: 91,
    category: "Jeans",
  },
  {
    id: 5,
    title: "Buscando a Mr. Goodbar - Jeans",
    detail: "Jeans cómodos y flexibles, perfectos para el uso diario.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Mancuernas-Hexagonales-de-Caucho-Mir-de-15-Kg-2-2-1000x1000.jpg",
    price: 5,
    stock: 49,
    category: "Jeans",
  },
  {
    id: 6,
    title: "Boda en la Noche Blanca - Jeans",
    detail: "Jeans ligeros y frescos, ideales para el verano.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Set-de-mancuernas-de-goma-redondas-sin-logo-de-25kg-a-30kg.-Total-390kg-12-pares-1000x1000.jpg",
    price: 2,
    stock: 73,
    category: "Jeans",
  },
  {
    id: 7,
    title: "Godzilla vs. Megalon - Jeans",
    detail: "Jeans exclusivos con estilo único y alta calidad.",
    img: "https://mirfitness.com.ar/wp-content/uploads/mancuernas-rec-en-goma-everlast-2-1000x1000.jpg",
    price: 55,
    stock: 5,
    category: "Jeans",
  },
  {
    id: 8,
    title: "La Casa de las Muñecas - Zapatillas",
    detail: "Zapatillas urbanas con suela antideslizante y durabilidad.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Tobillera-de-2kg-nuevo-disen%CC%83o-1000x1000.jpg",
    price: 47,
    stock: 39,
    category: "Sneakers",
  },
  {
    id: 9,
    title: "Estrellas y Rayas - Zapatillas",
    detail: "Zapatillas clásicas y versátiles con diseño cómodo.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Tobillera-de-3-Kg-MIR-Con-Ribete-2-1-1000x1000.jpg",
    price: 26,
    stock: 80,
    category: "Sneakers",
  },
  {
    id: 10,
    title: "Academia de Platón - Zapatillas",
    detail: "Zapatillas con suela acolchada y plantilla ergonómica.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Tobillera-de-1.5-KG-MIR-1-2-1000x1000.jpg",
    price: 19,
    stock: 69,
    category: "Sneakers",
  },
  {
    id: 11,
    title: "Hueso de Invierno - Zapatillas",
    detail: "Zapatillas deportivas ligeras y transpirables.",
    img: "https://mirfitness.com.ar/wp-content/uploads/Power-Rack-1000x1000.jpg",
    price: 35,
    stock: 72,
    category: "Sneakers",
  },
  {
    id: 12,
    title: "Piratas del Caribe - Zapatillas",
    detail: "Zapatillas elegantes con detalles sofisticados.",
    img: "https://mirfitness.com.ar/wp-content/uploads/w4-01-2.jpeg",
    price: 52,
    stock: 76,
    category: "Sneakers",
  },
];

