const data = [
  {
    id: 1,
    title: "Ángeles Ensangrentados - Remera",
    detail: "Remera de algodón suave con estampado único.",
    img: "https://image.spreadshirtmedia.net/image-server/v1/products/T943A2PA3767PT17X45Y2D186911900W19989H24989/views/1,width=378,height=378,appearanceId=2,backgroundColor=F2F2F2,modelId=296,crop=list/pequeno-diablo-en-estos-ojos-de-angel.jpg",
    price: 7,
    stock: 100,
    category: "T-shirt",
  },
  {
    id: 2,
    title: "Patrulla de Esquí - Camiseta",
    detail: "Camiseta deportiva de invierno, transpirable y cómoda.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvulnNOOGulEvURV158K6K-PLJBn0rgmhc1A&s",
    price: 5,
    stock: 73,
    category: "T-shirt",
  },
  {
    id: 3,
    title: "Ladybird Ladybird - Remera",
    detail: "Remera casual de algodón, ideal para cualquier ocasión.",
    img: "https://http2.mlstatic.com/D_NQ_NP_671388-MLA75960738963_042024-O.webp",
    price: 48,
    stock: 99,
    category: "T-shirt",
  },
  {
    id: 4,
    title: "Cannonball Run II - Jeans",
    detail: "Jeans clásicos, cómodos y perfectos para combinar.",
    img: "https://valentino-cdn.thron.com/delivery/public/image/valentino/67757d33-4e7b-477b-b79a-a0de1a77e0c9/ihqstx/std/500x0/BLUE-WASHED-DENIM-JEANS?quality=80&size=35&format=auto",
    price: 27,
    stock: 91,
    category: "Jeans",
  },
  {
    id: 5,
    title: "Buscando a Mr. Goodbar - Jeans",
    detail: "Jeans cómodos y flexibles, perfectos para el uso diario.",
    img: "https://www.rogersjeans.com.ar/wp-content/uploads/2019/09/Jean-Local.jpg",
    price: 5,
    stock: 49,
    category: "Jeans",
  },
  {
    id: 6,
    title: "Boda en la Noche Blanca - Jeans",
    detail: "Jeans ligeros y frescos, ideales para el verano.",
    img: "https://acdn.mitiendanube.com/stores/001/031/712/products/jean-cargo-alfonsina-1-31-518ba41b4ad02a004116917601269508-1024-1024.png",
    price: 2,
    stock: 73,
    category: "Jeans",
  },
  {
    id: 7,
    title: "Godzilla vs. Megalon - Jeans",
    detail: "Jeans exclusivos con estilo único y alta calidad.",
    img: "https://nacarindumentaria.com.ar/cdn/shop/products/IMG-20210526-WA0013_700x.jpg?v=1664369450",
    price: 55,
    stock: 5,
    category: "Jeans",
  },
  {
    id: 8,
    title: "La Casa de las Muñecas - Zapatillas",
    detail: "Zapatillas urbanas con suela antideslizante y durabilidad.",
    img: "https://acdn.mitiendanube.com/stores/003/962/317/products/23082023-img_7597-a84398e9a30ae2a33417059339869310-1024-1024.jpg",
    price: 47,
    stock: 39,
    category: "Sneakers",
  },
  {
    id: 9,
    title: "Estrellas y Rayas - Zapatillas",
    detail: "Zapatillas clásicas y versátiles con diseño cómodo.",
    img: "https://http2.mlstatic.com/D_NQ_NP_648328-MLA70431726766_072023-O.webp",
    price: 26,
    stock: 80,
    category: "Sneakers",
  },
  {
    id: 10,
    title: "Academia de Platón - Zapatillas",
    detail: "Zapatillas con suela acolchada y plantilla ergonómica.",
    img: "https://equipovallejo.vtexassets.com/arquivos/ids/321031-800-auto?v=638557213485400000&width=800&height=auto&aspect=true",
    price: 19,
    stock: 69,
    category: "Sneakers",
  },
  {
    id: 11,
    title: "Hueso de Invierno - Zapatillas",
    detail: "Zapatillas deportivas ligeras y transpirables.",
    img: "https://d368r8jqz0fwvm.cloudfront.net/46519-product_lg/zapatillas-de-mujer-seilas-gtx.jpg",
    price: 35,
    stock: 72,
    category: "Sneakers",
  },
  {
    id: 12,
    title: "Piratas del Caribe - Zapatillas",
    detail: "Zapatillas elegantes con detalles sofisticados.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD0K9ybdQ42Bq68-UKvDz1hI-nxDWwo2VsDw&s",
    price: 52,
    stock: 76,
    category: "Sneakers",
  },
];

